//
//  StyleKitName.h
//  ProjectName
//
//  Created by AuthorName on 14/11/3.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKit : NSObject

//// In trial version of PaintCode, the code generation is limited to one canvas

// Drawing Methods
+ (void)drawCanvas1:(CGFloat)progress;

//刻度表：
+ (void)drawCanves2:(CGFloat)pressure;



@end
